<<<<<<< HEAD:fac/migrations/0002_auto_20210322_1622.py
# Generated by Django 3.1.7 on 2021-03-22 22:22
=======
# Generated by Django 3.1.7 on 2021-03-22 21:17
>>>>>>> ec42c4d41b724630565962e997b039b79a727c88:fac/migrations/0002_auto_20210322_1517.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD:fac/migrations/0002_auto_20210322_1622.py
        ('inv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fac', '0001_initial'),
=======
        ('fac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0001_initial'),
>>>>>>> ec42c4d41b724630565962e997b039b79a727c88:fac/migrations/0002_auto_20210322_1517.py
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='uc',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='um',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturadet',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fac.facturaenc'),
        ),
        migrations.AddField(
            model_name='facturadet',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.producto'),
        ),
        migrations.AddField(
            model_name='facturadet',
            name='uc',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturadet',
            name='um',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
