# Generated by Django 3.1.7 on 2021-03-22 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0001_initial'),
        ('cmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comprasenc',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmp.proveedor'),
        ),
        migrations.AddField(
            model_name='comprasenc',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comprasdet',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmp.comprasenc'),
        ),
        migrations.AddField(
            model_name='comprasdet',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.producto'),
        ),
        migrations.AddField(
            model_name='comprasdet',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
