# Generated by Django 3.1.7 on 2021-03-17 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(default='Anónimo', max_length=50)),
                ('frase', models.TextField(blank=True, null=True)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.idioma')),
            ],
            options={
                'verbose_name_plural': 'Frases',
            },
        ),
    ]
